### ISSUE TITLE
Add test

### ISSUE THREAD

**Issue by EQuimper** [AppAndFlow/react-native-google-autocomplete#1]

**Comment by rockchalkwushock** [comment]
@EQuimper 

Going to start on this tonight, didn't have time to over the weekend. Do you want to add in CI/CD? I can set up CircleCi with `jest` and `semantic-release`. You just have to add `GH_TOKEN` & `NPM_TOKEN` as envvars in CircleCi and it will publish to NPM when pushing to master.

**Comment by EQuimper** [comment]
Yes good idea for circle :)
