### ISSUE TITLE
Empty locationResults

### ISSUE THREAD

**Issue by chaosLegacy** [AppAndFlow/react-native-google-autocomplete#11]
Hi, Great package sir,
I'm having an issue for displaying the autocomplete data provided from google API, I've followed all the steps in the readme file, I've created my API key and I've added it to the component.
When I start typing the locationResults is always empty, I don't understand is there a way to debug this to see if the problem is related to the API key or some issue in the library itself

`<GoogleAutoComplete apiKey={Global.GOOGLE_MAPS_API_KEY}`
                               ` debounce={debounce}`
                               ` minLength={minLength}> {({`
                     ` inputValue,`
                     ` handleTextChange,`
                     ` locationResults,`
                     ` fetchDetails,`
                      `isSearching,`
                 ` }) => (`
                    `<React.Fragment>`
                       ` <Input value={inputValue}`
                              ` onChangeText={handleTextChange}`
                               `placeholder={placeholder}`
                               `style={inputStyle}/>`
                        `{isSearching && <Spinner size='large'/>}`
                        `<View style={styles.mainView}>`
                            `<ScrollView style={styles.scrollViewStyle1}`
                                       ` contentContainerStyle={styles.homeView}>`
                                `<Text>data: {locationResults}</Text>`
                                `{locationResults.map((el, i) => (`
                                   ` <LocationItem`
                                       ` {...el}`
                                       ` fetchDetails={fetchDetails}`
                                       ` key={String(i)}`
                                    `/>`
                               ` ))}`
                           ` </ScrollView>`
                        `</View>`
                    `</React.Fragment>`
               ` )}`
            `</GoogleAutoComplete>`

<img width="1170" alt="screen shot 2018-09-10 at 2 56 11 am" src="https://user-images.githubusercontent.com/11313734/45272508-6ad8d980-b4a5-11e8-8c28-b262a966171a.png">

**Comment by YannickLeRoux** [comment]
I am having the same issue right now, did you figure it out yourself ?

**Comment by chaosLegacy** [comment]
Hi @YannickLeRoux It's actually a problem related to the key API its self I was using, if you can see in the screenshot I shared you can notice that I've got 82 errors related to my API key that wasn't working, so the solution is simply to change your API key.
Hope that will work. Let me know so I can close the issue once you've got things working with you.

**Comment by EQuimper** [comment]
I will check this weekend sorry about that.

**Comment by YeonwooSung** [comment]
I am currently having same error... Did someone figure out??

**Comment by YeonwooSung** [comment]
I think I figured out - This API error happens when you don't set up the payment account for the google api. So, if you use google api more than the limit, then the google api will automatically blocks your request.

**Comment by EQuimper** [comment]
Wow I didn't they block your request, I will try to check if they return another status code, maybe I can make the lib return a boolean when you hit a limit. What you think of this ?

**Comment by YeonwooSung** [comment]
@EQuimper Yeah, that would be great!

**Comment by EQuimper** [comment]
perfect I will do this, I'm open to pr also if you want to make it @YeonwooSung :)

**Comment by guiguerino** [comment]
I still have this error. Any solution?

**Comment by cfchacon10** [comment]
I still have this error as well. Some sort of error to let us know that it's being blocked would be great.

**Comment by EQuimper** [comment]
@cfchacon10 do the api key is web ? Someone did use android or ios api key but don't work. Here we use the web api.

**Comment by memartello** [comment]
They ask for a request web address for change to http web, google service have the option to set none. Im having the same issue

**Comment by EQuimper** [comment]
@memartello I will make a new video about how to setup this
