### ISSUE TITLE
Location or radius does not work 

### ISSUE THREAD

**Issue by georgeMorales** [AppAndFlow/react-native-google-autocomplete#22]
Location or radius does not work... @EQuimper, could you tell me what I'm doing wrong?
`<GoogleAutoComplete 
                    apiKey={API_KEY} 
                    debounce={500} 
                    minLength={3} 
                    language="es" 
                    queryTypes="establishment"
                    location="37.1848024, -5.7753099"
                    radius="35000"
                    components="country:es"
                >`

**Comment by EQuimper** [comment]
Hey @JorgeMoralesLopez did you try `radius={35000}` ?

**Comment by EQuimper** [comment]
@JorgeMoralesLopez Can you try version 0.1.6 :)

**Comment by JorgeMoralesLopez** [comment]
I have tried in all possible ways, radius = {20000} the console throws at me Warning: Failed prop type: Invalid prop `radius` of type` number` supplied to `GoogleAutoComplete`, expected` string`, I do not know how to put location location = "37.1848024, -5.7753099", or location = {{lat: 37.1848024, lng: -5.7753099}}
I have the version "^ 0.1.5" installed, I will try the one you tell me.
Thank you!

**Comment by EQuimper** [comment]
yes this one also take the version as a string. So you can do `radius="35000"`

**Comment by JorgeMoralesLopez** [comment]
I have installed version 0.1.6 and location does not work. Do not have any examples with radius and location working? He already tried it.

**Comment by EQuimper** [comment]
@JorgeMoralesLopez the version 0.1.6 was just a fix for radius. I'm currently working on the location right now

**Comment by JorgeMoralesLopez** [comment]
Ok, I did not understand well ... Thanks!

**Comment by EQuimper** [comment]
No problem my mistake

**Comment by JorgeMoralesLopez** [comment]
Please, when it is fixed, let me know, and if it is going to cost you a lot of time also to be able to look for another alternative. It is a feature that I need urgently.

**Comment by EQuimper** [comment]
@JorgeMoralesLopez Can you try version 0.1.7

I add props call latitude `lat: number` longitude `lng: number` if one is pass both are need.

**Comment by JorgeMoralesLopez** [comment]
@EQuimper, now if the location works. But the radius does not work, it appears in the list very distant establishments.
Radius tried it as a string and as a number.
I appreciate your effort!

**Comment by EQuimper** [comment]
Can you give me a picture of the response you get and the props you pass if possible. So location work just the radius ?

**Comment by JorgeMoralesLopez** [comment]
Sorry I didn't see this last message, summer is a crazy thing ...
Thank you!
Only the first result enters the range, radius ... The others do not.
It is true that the first is the closest.
![screenShot_radius](https://user-images.githubusercontent.com/25966648/64912604-0abce900-d732-11e9-8900-e647b5f4600e.png)

**Comment by JackJBlundell** [comment]
Hi there, this is an issue I am also facing.

When passing the prop radius, I am able to see inside of the react-native-google-autocomplete/dist/GoogleAutoComplete.js that the radius is being passed (And can be logged to the console).
However this makes no difference, i get a list of global addresses, using version 0.1.6 currently.

**Comment by EQuimper** [comment]
I will check for the issue. Maybe google did change something with their api. Will check that

**Comment by georgeMorales** [comment]
Yes, the radio feature doesn't work because searches for very far places appear by putting radius = "50000" for example. If this could be fixed it would be great.

**Comment by JackJBlundell** [comment]
Has this been fixed? Sorry to be a pain this is a vital part of the API though

**Comment by fuzexjj** [comment]
According to the Places API: 

> Location restrict
> You may also restrict results to the region defined by location and a radius parameter, by adding the "strictbounds" parameter. This instructs the Place Autocomplete service to return only results within that region.

Otherwise, you would get only _prefered_ result by **location** and **radius** but not _restricted_ by the area.

I will try to make PR

**Comment by JackJBlundell** [comment]
I have changed to another API, sorry.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
