### ISSUE TITLE
queryTypes='cities' does not work -> change to (cities)

### ISSUE THREAD

**Issue by glow319** [AppAndFlow/react-native-google-autocomplete#25]
Thanks for the awesome package.

I've found an issue with the queryTypes = 'cities'. Actually it doesn't give back any search results. After looking into the google api docs, I've found out that the correct name is '(cities)'. 
[https://developers.google.com/places/web-service/autocomplete#place_types]()

I've changed that in my project and now I get only city results. Would be great if this could be changed in the package.

**Comment by EQuimper** [comment]
THank you @glow319 I will do the change. Really appreciate it
