### ISSUE TITLE
How do you make the text input show the address of the location that was clicked? Please help me

### ISSUE THREAD

**Issue by quocbaovu15101996** [AppAndFlow/react-native-google-autocomplete#26]

**Comment by EQuimper** [comment]
This feature is more react stuff. You should have a state in your component call selectedPlace or something like that, when click on a row you set this place to this one. the text input should have the value equal to this selectedPlace

**Comment by EQuimper** [comment]
@quocbaovu15101996 did that answer your question

**Comment by EQuimper** [comment]
I will close the issue because of no response
