### ISSUE TITLE
AutoComlete by cities or zip-code

### ISSUE THREAD

**Issue by slatqh** [AppAndFlow/react-native-google-autocomplete#27]
Hi, 
Thanks for awesome packages. 
I saw the issue about queryTypes='cities' doesn't return anything. Hope you fix it soon. 
Also I'm wondering if I can autocomplete a zip code using a 'postal_code' types?

What I'm trying to achieve is when user start typing 900..  for example, it's given back a zip codes. 

Thanks.

**Comment by EQuimper** [comment]
@slatqh if google let us do this I will be happy to add this. I didn't check yet but can check this weekend. Do you know if this is possible ?

**Comment by cfchacon10** [comment]
Hi, I put 'cities' as one of the queryTypes and it is also returning nothing. Has this already been taken care of? Thank you.

**Comment by cfchacon10** [comment]
Just figured it out a few minutes later haha you have to put "(cities)" because that is how its stated in the Google API docs. I tried this and it worked, but you should update this in your code because it thinks the correct way is "cities" and throwing a warning at me. Thanks!

**Comment by EQuimper** [comment]
@cfchacon10 I'm open to pr if you want :) Else I will do this but thank you :)
