### ISSUE TITLE
Start with current place location

### ISSUE THREAD

**Issue by zapcriativo** [AppAndFlow/react-native-google-autocomplete#30]
Hi!

I have 2 fields in my app, origin and destiny with location use, and I want the first one to come with the initial location already populated.

Is it possible to do this in the module, passing latitude and longitude?

Example in image below 

Regards

<img width="371" alt="image" src="https://user-images.githubusercontent.com/7153803/67912584-299fff00-fb69-11e9-97fa-b6e43a96018c.png">

**Comment by thgcst** [comment]
I'm also looking forward to this
