### ISSUE TITLE
Places Types

### ISSUE THREAD

**Issue by zapcriativo** [AppAndFlow/react-native-google-autocomplete#32]
Hi!

Please, how to search with multiple types as per google documentation

![image](https://user-images.githubusercontent.com/7153803/68996939-94e31400-087f-11ea-8b8c-d7fc282879d3.png)

**Comment by zapcriativo** [comment]
Please, can anyone help me?

**Comment by zapcriativo** [comment]
Its worked with 

queryTypes={'geocode|establishment'}

**Comment by EQuimper** [comment]
@zapcriativo sorry, was in moving process and didn't have the net until yesterdays. Sorry for that, happy you did find the answer. Do you want to add this to the readme and do a pr for this ? :) So sorry again
