### ISSUE TITLE
Problem with radius.

### ISSUE THREAD

**Issue by p4ri4s** [AppAndFlow/react-native-google-autocomplete#34]
Hi,
I have problem with property radius, no matter what value I set, it doesn't affect the displayed results.
![radius](https://user-images.githubusercontent.com/46496087/70823666-bed91900-1de0-11ea-9fb7-f8a029d7f861.PNG)

**Comment by MikhailVasiliev** [comment]
> Hi,
> I have problem with property radius, no matter what value I set, it doesn't affect the displayed results.
> ![radius](https://user-images.githubusercontent.com/46496087/70823666-bed91900-1de0-11ea-9fb7-f8a029d7f861.PNG)

on your screenshot you set 'latitude' to both fields (lat and lng), maybe that's a reason
