### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by RWOverdijk** [AppAndFlow/react-native-google-autocomplete#37]
This library looks like it's _exactly_ what I need. There's one teensy issue, which is that I also use react-native-web and it fails on a cors error.

I tried setting cors to no-cors locally to test but that doesn't seem to be enough.

**Comment by aviemet** [comment]
Did you happen to find a workaround for this? I have the exact same issue

**Comment by RWOverdijk** [comment]
I did, I forked it and wrote my own functions for web :)

**Comment by EQuimper** [comment]
@RWOverdijk did you need to make big change or ? Can I see it ? I want this feature, but the last time I did touch the web is more than 3 years ago so ... :)

**Comment by RWOverdijk** [comment]
@EQuimper It's not too bed. You'll need to add your own require (index.html) or create an injector.

From there it's just checking if it's web:

`const isWeb = Platform.OS === 'web'`

And then making the appropriate changes:

```js
    // GoogleService._search example:
    if (isWeb) {
      const service = new google.maps.places.AutocompleteService()

      return new Promise(resolve => {
        service.getPlacePredictions({ input: term, types: null }, (predictions, status) => resolve({ predictions, status }))
      })
    }
```

Etc. I did some other things as well to make it more similar (lowest common denominator) but it works alright.

**Comment by hiwyn** [comment]
why did u close the @RWOverdijk issue @EQuimper ?
is it working on web somehow?
i've open a new issue: https://github.com/AppAndFlow/react-native-google-autocomplete/issues/47
should i give it up?

**Comment by MiguelNiblock** [comment]
> 



> @EQuimper It's not too ~bed~ bad _(I guess I'm tired lol)_. You'll need to add your own require of the google maps sdk (index.html) or create an injector.
> 
> ```
> <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=your_key&libraries=places"></script>
> ```
> 
> Given that you already know the key in the code, I opted to use an injector:
> 
> ```js
> const inject = () => {
>   if (document.getElementById('google-maps-script')) return;
> 
>   const script= document.createElement('script');
>   
>   script.setAttribute('id', 'google-maps-script');
>   script.src = "https://maps.googleapis.com/maps/api/js?key=your_key&libraries=places";
>   document.head.appendChild(script);
> ```
> 
> From there it's just checking if it's web:
> 
> `const isWeb = Platform.OS === 'web'`
> 
> And then making the appropriate changes:
> 
> ```js
>     // GoogleService._search example:
>     if (isWeb) {
>       const service = new google.maps.places.AutocompleteService()
> 
>       return new Promise(resolve => {
>         service.getPlacePredictions({ input: term, types: null }, (predictions, status) => resolve({ predictions, status }))
>       })
>     }
> ```
> 
> Etc. I did some other things as well to make it more similar (lowest common denominator) but it works alright.
> 
> I wrote this blind, and seeing how I'm a bit tired I might have made a couple of mistakes but I'm sure you get the gist.

Do you have sample code of this tweak fully implemented? These changes have not been added to this library so it still doesn't work on web.

**Comment by EQuimper** [comment]
This will now work with version 2.0.0 which is in release candidate right now :)
