### ISSUE TITLE
locationResults always return []

### ISSUE THREAD

**Issue by bfraiman** [AppAndFlow/react-native-google-autocomplete#39]
When Im trying to fetch places, locationResults always give me empty array. I dont know if I need to change my configuration of maps or if it’s an library error.

**Comment by EQuimper** [comment]
I use the library on more than 5 projects and don't have the issues. Did you make your api key a web key ?

**Comment by EQuimper** [comment]
Some people did get the issue the reason was they make the api key as an ios or android key but the one you need is web.
