### ISSUE TITLE
minLength doesn't work

### ISSUE THREAD

**Issue by georgeMorales** [AppAndFlow/react-native-google-autocomplete#41]
minLength like radio doesn't work either, I always get 5 searches and I want 3 to appear...

**Comment by EQuimper** [comment]
Umh the minLength was the amount of characters need before making any api call. `optional - default 2 - this is the min length of the term search before start`

**Comment by EQuimper** [comment]
```ts
  private _handleTextChange = (inputValue: string) => {
    if (this.props.apiKey == null) {
      throw new Error('Api Key is required');
    }

    this.setState({
      inputValue,
    });

    if (inputValue.length >= this.props.minLength!) {
      this._search(inputValue);
    }
  };
```

**Comment by georgeMorales** [comment]
Sorry, I got confused ... What I wanted to say is that when you do a search you get 5 options and I would like to reduce it to 3 ...
It's possible?
And as for the radio, would it be possible for it to work?
Thank you for responding quickly!

**Comment by EQuimper** [comment]
@georgeMorales I see what you mean. Can google api do this ? If yes I can plug that. But if not, I'm not sure how I can force it

**Comment by georgeMorales** [comment]
I perfectly understand. If you make the radio work and when I look for an address or establishment, if I am in Spain that does not appear from Colombia, Mexico, etc ... With that I would be more than satisfied.
Thank you!
