### ISSUE TITLE
How do i handle promise rejections?

### ISSUE THREAD

**Issue by arf1e** [AppAndFlow/react-native-google-autocomplete#45]
Is there a way to handle network request errors? 
The lib is good, but when testing worst-case scenario with no internet connection my RN Debugger goes yellow and I can`t find a way to handle it.
Would be great if the lib had some render prop for showing the error state.

**Comment by EQuimper** [comment]
@arf1e this is a good idea. A really good one. I will try to add that this weekend. Thank you
